### ISSUE TITLE
support multiple checksums

### ISSUE THREAD

**Issue by mgrauer** [brianhelba/cookiecutter-django-girder#13]
It'd be good to know that the checksum is a sha512, so perhaps renaming to sha512 or allowing multiple different checksums with the name of the hash algorithm would be helpful.

**Comment by brianhelba** [comment]
For an example project like this, I think supporting multiple checksums doesn't add any value. Perhaps if we wanted to show an example of how support reusable parameterized field defintions, the checksum fields could be a good starting point, but I think such functionality is be far too complex for the cookiecutter in its present state.

**Comment by brianhelba** [comment]
I considered using the field name of `sha512` at first, but since the intention is to provide an example of the capability of computing file checksums, I think the current name presents that idea to viewers in the simplest way. Under this perspective, the use of SHA512 is simply an implementation detail.

**Comment by brianhelba** [comment]
@mgrauer I'm going to close this as WONTFIX for both suggestions, sorry. :slightly_frowning_face:

**Comment by mgrauer** [comment]
No need to apologize, reading this discussion helps me get clarity on the scope of this repo.
